/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class berlin_iconn_rbm_NativeRBM */

#ifndef _Included_berlin_iconn_rbm_NativeRBM
#define _Included_berlin_iconn_rbm_NativeRBM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    createNativeRBM
 * Signature: ([FI[FII[FFI)V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_createNativeRBM
  (JNIEnv *, jobject, jfloatArray, jint, jfloatArray, jint, jint, jfloatArray, jfloat, jint);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    deleteNativeRBM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_deleteNativeRBM
  (JNIEnv *, jobject);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    trainNativeWithoutError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_trainNativeWithoutError
  (JNIEnv *, jobject);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    trainNativeWithError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_trainNativeWithError
  (JNIEnv *, jobject);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    trainNativeBinarizedWithoutError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_trainNativeBinarizedWithoutError
  (JNIEnv *, jobject);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    trainNativeBinarizedWithError
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_trainNativeBinarizedWithError
  (JNIEnv *, jobject);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    getNativeWeights
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_berlin_iconn_rbm_NativeRBM_getNativeWeights
  (JNIEnv *, jobject);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    getNativeError
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_berlin_iconn_rbm_NativeRBM_getNativeError
  (JNIEnv *, jobject);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    setNativeWeights
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_setNativeWeights
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    setNativeData
 * Signature: ([FII[F)V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_setNativeData
  (JNIEnv *, jobject, jfloatArray, jint, jint, jfloatArray);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    setNativeLearningRate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_setNativeLearningRate
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
