/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class berlin_iconn_rbm_NativeRBM */

#ifndef _Included_berlin_iconn_rbm_NativeRBM
#define _Included_berlin_iconn_rbm_NativeRBM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    createNativeRBM
 * Signature: ([FIII)I
 */
JNIEXPORT jint JNICALL Java_berlin_iconn_rbm_NativeRBM_createNativeRBM
  (JNIEnv *, jobject, jfloatArray, jint, jint, jint);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    deleteNativeRBM
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_deleteNativeRBM
  (JNIEnv *, jobject, jint);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    trainNativeWithoutError
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_trainNativeWithoutError
  (JNIEnv *, jobject, jint);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    trainNativeWithError
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_trainNativeWithError
  (JNIEnv *, jobject, jint);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    trainNativeBinarizedWithoutError
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_trainNativeBinarizedWithoutError
  (JNIEnv *, jobject, jint);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    trainNativeBinarizedWithError
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_trainNativeBinarizedWithError
  (JNIEnv *, jobject, jint);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    getNativeWeights
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_berlin_iconn_rbm_NativeRBM_getNativeWeights
  (JNIEnv *, jobject, jint);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    getNativeError
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_berlin_iconn_rbm_NativeRBM_getNativeError
  (JNIEnv *, jobject, jint);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    setNativeWeights
 * Signature: (I[FII)V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_setNativeWeights
  (JNIEnv *, jobject, jint, jfloatArray, jint, jint);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    setNativeData
 * Signature: (I[FI)V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_setNativeData
  (JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    setNativeLearningRate
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_berlin_iconn_rbm_NativeRBM_setNativeLearningRate
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    runHidden
 * Signature: (I[FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_berlin_iconn_rbm_NativeRBM_runHidden
  (JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    runVisible
 * Signature: (I[FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_berlin_iconn_rbm_NativeRBM_runVisible
  (JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     berlin_iconn_rbm_NativeRBM
 * Method:    error
 * Signature: (I[FI)F
 */
JNIEXPORT jfloat JNICALL Java_berlin_iconn_rbm_NativeRBM_error
  (JNIEnv *, jobject, jint, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
